services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - '5450:5432'
    environment:
      POSTGRES_DB: diplomDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d diplomDB']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis_db
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/diplomDB
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
  redisdata:
